**FIRST THINGS FIRST**

In [1]:
import pandas as pd

**Reading the 2026-27 CSV file into a DataFrame**

In [2]:
df_2627 = pd.read_csv("C:/Users/g32ma/dataProjects/opening night rosters/data/Opening night rosters - 202627.csv")

**Reading the 2025-26 CSV file into a DataFrame**

In [3]:
df_2526 = pd.read_csv("C:/Users/g32ma/dataProjects/opening night rosters/data/Opening night rosters - 202526.csv")

**Tagging every row in df_2526 with its season label so the source is clear after merging**

In [4]:
df_2526['Season'] = '2025-26'

**Confirming the column was added**

In [5]:
df_2526.head(3)

     Country           Name               Team   Season
0  Australia  Dyson Daniels      Atlanta Hawks  2025-26
1  Australia     Josh Green  Charlotte Hornets  2025-26
2  Australia    Josh Giddey      Chicago Bulls  2025-26

**Tagging every row in df_2627 with its season label so the source is clear after merging**

In [6]:
df_2627['Season'] = '2026-27'

**Confirming the column was added**

In [7]:
df_2627.head(3)

     Country           Name           Team   Season
0  Australia  Dyson Daniels  Atlanta Hawks  2026-27
1  Australia   Jock Landale  Atlanta Hawks  2026-27
2  Australia    Josh Giddey  Chicago Bulls  2026-27

**Stacking both season tables together, using ignore_index=True to reset the row index and avoid duplicate numbers**

In [8]:
df_master = pd.concat([df_2526, df_2627], ignore_index=True)

**Confirming by checking random sample**

In [9]:
df_master.sample(5)

         Country              Name                Team   Season
241       Serbia  Tristan Vukčević  Washington Wizards  2026-27
127  Switzerland    Kyshawn George  Washington Wizards  2025-26
45        Canada        Will Riley  Washington Wizards  2025-26
76        France   Bilal Coulibaly  Washington Wizards  2025-26
120        Spain     Hugo González      Boston Celtics  2025-26

**Create a basic pivot table counting players per country for each season**

In [10]:
country_pivot = df_master.pivot_table(index='Country', columns='Season', values='Name', aggfunc='count', fill_value=0)

**Confirming our pivot table was created**

In [11]:
country_pivot.head()

Season                  2025-26  2026-27
Country
Australia                    13        9
Austria                       1        1
Bahamas                       3        3
Belgium                       2        2
Bosnia and Herzegovina        1        1

**Sorting the table to see the top countries in the 2026-27 season**

In [12]:
country_pivot = country_pivot.sort_values(by='2026-27', ascending=False)
country_pivot.head()

Season     2025-26  2026-27
Country
France          19       17
Canada          23       16
Australia       13        9
Germany          7        7
Nigeria          2        6

**Calculating absolute change from 2025-26 to 2026-27**

In [13]:
country_pivot['Absolute_Change'] = (
    country_pivot['2026-27'] - country_pivot['2025-26']
)
country_pivot.head()

Season     2025-26  2026-27  Absolute_Change
Country
France          19       17               -2
Canada          23       16               -7
Australia       13        9               -4
Germany          7        7                0
Nigeria          2        6                4

**Sorting by top change**

In [14]:
country_pivot = country_pivot.sort_values(by='Absolute_Change', ascending=False)
country_pivot.head()

Season       2025-26  2026-27  Absolute_Change
Country
Nigeria            2        6                4
Spain              2        5                3
Netherlands        1        3                2
Türkiye            0        2                2
Estonia            0        1                1

**Finding largest drop in absolute change**

In [15]:
country_pivot = country_pivot.sort_values(by='Absolute_Change', ascending=True)
country_pivot.head()

Season     2025-26  2026-27  Absolute_Change
Country
Canada          23       16               -7
Australia       13        9               -4
Greece           3        1               -2
France          19       17               -2
Sweden           2        1               -1

**Calculating the year-over-year percentage change for each country**

In [16]:
country_pivot['Pct_Change'] = (country_pivot['Absolute_Change'] / country_pivot['2025-26']) * 100

country_pivot.head()

Season     2025-26  2026-27  Absolute_Change  Pct_Change
Country
Canada          23       16               -7  -30.434783
Australia       13        9               -4  -30.769231
Greece           3        1               -2  -66.666667
France          19       17               -2  -10.526316
Sweden           2        1               -1  -50.000000

**Sorting by top change**

In [17]:
country_pivot = country_pivot.sort_values(by='Pct_Change', ascending=False)
country_pivot.head(15)

Season          2025-26  2026-27  Absolute_Change  Pct_Change
Country
Estonia               0        1                1         inf
Türkiye               0        2                2         inf
Mexico                0        1                1         inf
Netherlands           1        3                2       200.0
Nigeria               2        6                4       200.0
Spain                 2        5                3       150.0
Senegal               2        3                1        50.0
Germany               7        7                0         0.0
Croatia               3        3                0         0.0
China                 1        1                0         0.0
Brazil                1        1                0         0.0
Czech Republic        1        1                0         0.0
Portugal              1        1                0         0.0
Israel                2        2                0         0.0
Guinea                1        1                0         0.0

**And largest decline**

In [18]:
country_pivot = country_pivot.sort_values(by='Pct_Change', ascending=True)
country_pivot.head(15)

Season,2025-26,2026-27,Absolute_Change,Pct_Change
Country,,,,
Mali,1,0,-1,-100.000000
Turkey,1,0,-1,-100.000000
St. Lucia,1,0,-1,-100.000000
Greece,3,1,-2,-66.666667
Sweden,2,1,-1,-50.000000
Ukraine,2,1,-1,-50.000000
Democratic Republic of the Congo,3,2,-1,-33.333333
Lithuania,3,2,-1,-33.333333
Australia,13,9,-4,-30.769231
Canada,23,16,-7,-30.434783
United Kingdom,4,3,-1,-25.000000
Cameroon,4,3,-1,-25.000000
France,19,17,-2,-10.526316
Germany,7,7,0,0.000000
Israel,2,2,0,0.000000

**Moving on to players by club. We start with creating a basic pivot table counting players per club for each season**

In [19]:
team_pivot = df_master.pivot_table(index='Team', columns='Season', values='Name', aggfunc='count', fill_value=0)

**Confirming our pivot table was created**

In [20]:
team_pivot.head()

Season             2025-26  2026-27
Team
Atlanta Hawks           10        6
Boston Celtics           5        3
Brooklyn Nets            3        4
Charlotte Hornets        3        4
Chicago Bulls            5        4

**Sorting the table to see clubs with the most international players on opening night roster in the 2026-27 season**

In [21]:
team_pivot = team_pivot.sort_values(by='2026-27', ascending=False)
team_pivot.head()

Season                  2025-26  2026-27
Team
Dallas Mavericks              5        7
Miami Heat                    6        7
Washington Wizards            5        7
Philadelphia 76ers            3        6
Portland Trail Blazers        7        6

**Calculating absolute change from 2025-26 to 2026-27**

In [22]:
team_pivot['Absolute_Change'] = (team_pivot['2026-27'] - team_pivot['2025-26']
)
team_pivot.head()

Season                  2025-26  2026-27  Absolute_Change
Team
Dallas Mavericks              5        7                2
Miami Heat                    6        7                1
Washington Wizards            5        7                2
Philadelphia 76ers            3        6                3
Portland Trail Blazers        7        6               -1

**Sorting by top change**

In [23]:
team_pivot = team_pivot.sort_values(by='Absolute_Change', ascending=False)
team_pivot.head()

Season               2025-26  2026-27  Absolute_Change
Team
Philadelphia 76ers         3        6                3
Dallas Mavericks           5        7                2
Washington Wizards         5        7                2
Cleveland Cavaliers        2        4                2
Houston Rockets            4        5                1

**And steepest drop**

In [24]:
team_pivot = team_pivot.sort_values(by='Absolute_Change', ascending=True)
team_pivot.head()

Season              2025-26  2026-27  Absolute_Change
Team
Atlanta Hawks            10        6               -4
San Antonio Spurs         5        2               -3
Los Angeles Lakers        5        2               -3
New York Knicks           6        3               -3
LA Clippers               5        3               -2

**Our next and final stop is continents. I will use here the same dictionary I used for my spring project**

In [25]:
country_to_continent = {
    'France': 'Europe',
    'Serbia': 'Europe',
    'Croatia': 'Europe',
    'Germany': 'Europe',
    'Spain': 'Europe',
    'Lithuania': 'Europe',
    'Turkey': 'Europe',
    'Greece': 'Europe',
    'Russia': 'Europe',
    'Slovenia': 'Europe',
    'Ukraine': 'Europe',
    'Italy': 'Europe',
    'United Kingdom': 'Europe',
    'Netherlands': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'Georgia': 'Europe',
    'Latvia': 'Europe',
    'Montenegro': 'Europe',
    'Czech Republic': 'Europe',
    'Israel': 'Europe',
    'Poland': 'Europe',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Belgium': 'Europe',
    'Finland': 'Europe',
    'Estonia': 'Europe',
    'Austria': 'Europe',
    'Bulgaria': 'Europe',
    'Denmark': 'Europe',
    'Ireland': 'Europe',
    'Macedonia': 'Europe',
    'Portugal': 'Europe',
    'Romania': 'Europe',
    'Scotland': 'Europe',
    'Canada': 'North America',
    'Dominican Republic': 'North America',
    'Puerto Rico': 'North America',
    'Jamaica': 'North America',
    'Mexico': 'North America',
    'Bahamas': 'North America',
    'Haiti': 'North America',
    'US Virgin Islands': 'North America',
    'Antigua and Barbuda': 'North America',
    'Belize': 'North America',
    'British Virgin Islands': 'North America',
    'Cuba': 'North America',
    'Nicaragua': 'North America',
    'Panama': 'North America',
    'Saint Lucia': 'North America',
    'St. Vincent & Grenadines': 'North America',
    'Trinidad and Tobago': 'North America',
    'Senegal': 'Africa',
    'Nigeria': 'Africa',
    'Cameroon': 'Africa',
    'South Sudan': 'Africa',
    'DRC': 'Africa',
    'Mali': 'Africa',
    'Congo': 'Africa',
    'Gabon': 'Africa',
    'Ghana': 'Africa',
    'Guinea': 'Africa',
    'Angola': 'Africa',
    'Cabo Verde': 'Africa',
    'Egypt': 'Africa',
    'Sudan': 'Africa',
    'Tanzania': 'Africa',
    'Tunisia': 'Africa',
    'Brazil': 'South America',
    'Argentina': 'South America',
    'Venezuela': 'South America',
    'Colombia': 'South America',
    'Uruguay': 'South America',
    'Australia': 'Oceania',
    'New Zealand': 'Oceania',
    'China': 'Asia',
    'Japan': 'Asia',
    'Iran': 'Asia',
    'Lebanon': 'Asia',
    'South Korea': 'Asia',
}

**Now, we will create a new Continent column in df_master by mapping the Country values using our dictionary**

In [26]:
df_master['Continent'] = df_master['Country'].map(country_to_continent)
df_master.head()

     Country              Name                 Team   Season Continent
0  Australia     Dyson Daniels        Atlanta Hawks  2025-26   Oceania
1  Australia        Josh Green    Charlotte Hornets  2025-26   Oceania
2  Australia       Josh Giddey        Chicago Bulls  2025-26   Oceania
3  Australia  Lachlan Olbrich*        Chicago Bulls  2025-26   Oceania
4  Australia     Luke Travers*  Cleveland Cavaliers  2025-26   Oceania

**Let's check a random sample too shall we**

In [27]:
df_master.sample(7)

,Country,Name,Team,Season,Continent
132,United Kingdom,OG Anunoby,New York Knicks,2025-26,Europe
118,South Sudan,Khaman Maluach,Phoenix Suns,2025-26,Africa
158,Canada,Jamal Murray,Denver Nuggets,2026-27,North America
130,Ukraine,Max Shulga*,Boston Celtics,2025-26,Europe
59,France,Zaccharie Risacher,Atlanta Hawks,2025-26,Europe
34,Canada,Brandon Clarke,Memphis Grizzlies,2025-26,North America
58,Finland,Lauri Markkanen,Utah Jazz,2025-26,Europe

**Grouping and counting international players by continent**

In [28]:
continent_pivot = df_master.pivot_table(
    index='Continent', columns='Season', values='Name', aggfunc='count', fill_value=0
)
continent_pivot = continent_pivot[['2025-26', '2026-27']]
continent_pivot.head(6)

Season         2025-26  2026-27
Continent
Africa              12       15
Asia                 2        2
Europe              73       70
North America       29       23
Oceania             14       10
South America        1        1

**Calculating absolute change**

In [29]:
continent_pivot['Absolute_Change'] = (
    continent_pivot['2026-27'] - continent_pivot['2025-26']
)
continent_pivot.head(6)

Season         2025-26  2026-27  Absolute_Change
Continent
Africa              12       15                3
Asia                 2        2                0
Europe              73       70               -3
North America       29       23               -6
Oceania             14       10               -4
South America        1        1                0

**let's export our country dataframe to csv so that we can work with it datawrapper**

In [30]:
country_pivot.to_csv('nba_countries_for_map.csv')

**let's convert the rest of our findings to csv files as well**

In [31]:
continent_pivot.to_csv('nba_continents.csv')
team_pivot.to_csv('nba_teams.csv')